/*
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoodPortion {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    #[serde(rename = "dataPoints", skip_serializing_if = "Option::is_none")]
    pub data_points: Option<i32>,
    #[serde(rename = "gramWeight", skip_serializing_if = "Option::is_none")]
    pub gram_weight: Option<f32>,
    #[serde(rename = "minYearAcquired", skip_serializing_if = "Option::is_none")]
    pub min_year_acquired: Option<i32>,
    #[serde(rename = "modifier", skip_serializing_if = "Option::is_none")]
    pub modifier: Option<String>,
    #[serde(rename = "portionDescription", skip_serializing_if = "Option::is_none")]
    pub portion_description: Option<String>,
    #[serde(rename = "sequenceNumber", skip_serializing_if = "Option::is_none")]
    pub sequence_number: Option<i32>,
    #[serde(rename = "measureUnit", skip_serializing_if = "Option::is_none")]
    pub measure_unit: Option<Box<models::MeasureUnit>>,
}

impl FoodPortion {
    pub fn new() -> FoodPortion {
        FoodPortion {
            id: None,
            amount: None,
            data_points: None,
            gram_weight: None,
            min_year_acquired: None,
            modifier: None,
            portion_description: None,
            sequence_number: None,
            measure_unit: None,
        }
    }
}

