/*
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InlineResponse200 {
    AbridgedFoodItem(Box<models::AbridgedFoodItem>),
    BrandedFoodItem(Box<models::BrandedFoodItem>),
    FoundationFoodItem(Box<models::FoundationFoodItem>),
    SrLegacyFoodItem(Box<models::SrLegacyFoodItem>),
    SurveyFoodItem(Box<models::SurveyFoodItem>),
}

impl Default for InlineResponse200 {
    fn default() -> Self {
        Self::AbridgedFoodItem(Default::default())
    }
}

