/*
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InputFoodFoundation : applies to Foundation foods. Not all inputFoods will have all fields.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputFoodFoundation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "foodDescription", skip_serializing_if = "Option::is_none")]
    pub food_description: Option<String>,
    #[serde(rename = "inputFood", skip_serializing_if = "Option::is_none")]
    pub input_food: Option<Box<models::SampleFoodItem>>,
}

impl InputFoodFoundation {
    /// applies to Foundation foods. Not all inputFoods will have all fields.
    pub fn new() -> InputFoodFoundation {
        InputFoodFoundation {
            id: None,
            food_description: None,
            input_food: None,
        }
    }
}

