/*
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NutrientAnalysisDetails {
    #[serde(rename = "subSampleId", skip_serializing_if = "Option::is_none")]
    pub sub_sample_id: Option<i32>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    #[serde(rename = "nutrientId", skip_serializing_if = "Option::is_none")]
    pub nutrient_id: Option<i32>,
    #[serde(rename = "labMethodDescription", skip_serializing_if = "Option::is_none")]
    pub lab_method_description: Option<String>,
    #[serde(rename = "labMethodOriginalDescription", skip_serializing_if = "Option::is_none")]
    pub lab_method_original_description: Option<String>,
    #[serde(rename = "labMethodLink", skip_serializing_if = "Option::is_none")]
    pub lab_method_link: Option<String>,
    #[serde(rename = "labMethodTechnique", skip_serializing_if = "Option::is_none")]
    pub lab_method_technique: Option<String>,
    #[serde(rename = "nutrientAcquisitionDetails", skip_serializing_if = "Option::is_none")]
    pub nutrient_acquisition_details: Option<Vec<models::NutrientAcquisitionDetails>>,
}

impl NutrientAnalysisDetails {
    pub fn new() -> NutrientAnalysisDetails {
        NutrientAnalysisDetails {
            sub_sample_id: None,
            amount: None,
            nutrient_id: None,
            lab_method_description: None,
            lab_method_original_description: None,
            lab_method_link: None,
            lab_method_technique: None,
            nutrient_acquisition_details: None,
        }
    }
}

